# -*- coding: utf-8 -*-
"""CustomerChurn - Telco

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ckw30HJE5UeWSoAHYuweovB3RXJwQhv
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install category_encoders==2.*
# !pip install xgboost==1.3.2
# !pip install pdpbox
# !pip install shap

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from category_encoders import OrdinalEncoder, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score, validation_curve, KFold, GridSearchCV, RandomizedSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

from xgboost import XGBRegressor, XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.inspection import permutation_importance

from pdpbox.pdp import PDPIsolate, PDPInteract
from pdpbox.info_plots import TargetPlot, InteractTargetPlot
import shap
import warnings

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('telco.csv', encoding = 'latin1')

df.head()

def wrangle(filepath):
    df = pd.read_csv(filepath, encoding = 'latin1')
    df.drop(columns = ['Country', 'State'])
    return df

df = wrangle('telco.csv')
